cmdkey /list | ForEach-Object{if($_ -like "*target=TERMSRV/*"){cmdkey /del:($_ -replace " ","" -replace "Target:","")}}

echo "Connecting to somethingspecial.cloudapp.net"

$Server="somethingspecial.cloudapp.net"

$Port="49982"

$User="Administrator"

$Password="AdminPassword"

cmdkey /add:$Server /user:$User /pass:$Password

mstsc /v:$Server:$Port
